/** One key factory per context (CONVENTIONS §7), so invalidation is never a guess. */
export const keys = {
  productTypes: ['product-types'] as const,
  categories: ['categories'] as const,
  products: (filter?: object) => (filter ? ['products', filter] as const : ['products'] as const),
  product: (id: string) => ['product', id] as const,
  skus: (filter?: object) => (filter ? ['skus', filter] as const : ['skus'] as const),
  vendorCodes: ['vendor-codes'] as const,
  vendors: (filter?: object) => (filter ? ['vendors', filter] as const : ['vendors'] as const),
  vendor: (id: string) => ['vendor', id] as const,
  priceLists: ['price-lists'] as const,
  priceList: (id: string) => ['price-list', id] as const,
  discountCeilings: ['discount-ceilings'] as const,
  settings: ['settings'] as const,
  toggles: ['feature-toggles'] as const,
  ceilings: ['ceilings'] as const,
  commissionRates: ['commission-rates'] as const,
  targets: (period?: string) => (period ? ['targets', period] as const : ['targets'] as const),
  standings: (period?: string) => (period ? ['standings', period] as const : ['standings'] as const),
  myStanding: (period?: string) => (period ? ['my-standing', period] as const : ['my-standing'] as const),
  trends: (filter: object) => ['trends', filter] as const,
  reorder: ['reorder'] as const,
  purchaseOrders: (filter?: object) => (filter ? ['purchase-orders', filter] as const : ['purchase-orders'] as const),
  purchaseOrder: (id: string) => ['purchase-order', id] as const,
  incoming: ['incoming'] as const,
  stock: (filter?: object) => (filter ? ['stock', filter] as const : ['stock'] as const),
  skuStock: (id: string) => ['sku-stock', id] as const,
  lots: (lot: string) => ['lots', lot] as const,
  notifications: ['notifications'] as const,
  vehicles: ['vehicles'] as const,
  vehicle: (id: string) => ['vehicle', id] as const,
  loads: (filter?: object) => (filter ? ['vehicle-loads', filter] as const : ['vehicle-loads'] as const),
  vehicleReturns: (id: string) => ['vehicle-returns', id] as const,
  sellers: ['sellers'] as const,
  today: ['attendance-today'] as const,
  attendance: (filter?: object) => (filter ? ['attendance', filter] as const : ['attendance'] as const),
  myVehicle: ['my-vehicle'] as const,
  handovers: ['vehicle-handovers'] as const,
  closingStock: (filter?: object) => (filter ? ['closing-stock', filter] as const : ['closing-stock'] as const),
  zones: ['check-in-zones'] as const,
  stores: (filter?: object) => (filter ? ['stores', filter] as const : ['stores'] as const),
  store: (id: string) => ['store', id] as const,
  storeLedger: (id: string) => ['store-ledger', id] as const,
  storeOptions: ['store-options'] as const,
  sales: (filter?: object) => (filter ? ['sales', filter] as const : ['sales'] as const),
  sale: (id: string) => ['sale', id] as const,
  saleOptions: (storeId: string) => ['sale-options', storeId] as const,
  cashInHand: ['cash-in-hand'] as const,
  auditLog: (filter?: object) => (filter ? ['audit-log', filter] as const : ['audit-log'] as const),
  dispatchOrders: (filter?: object) => (filter ? ['dispatch-orders', filter] as const : ['dispatch-orders'] as const),
  dispatchOrder: (id: string) => ['dispatch-order', id] as const,
  dispatchOptions: (storeId: string) => ['dispatch-options', storeId] as const,
  dispatchStores: (search: string) => ['dispatch-stores', search] as const,
  returnable: (saleId: string) => ['returnable', saleId] as const,
  returns: (filter?: object) => (filter ? ['returns', filter] as const : ['returns'] as const),
  return: (id: string) => ['return', id] as const,
  salesMonth: ['sales-month'] as const,
  settlements: (filter?: object) => (filter ? ['settlements', filter] as const : ['settlements'] as const),
  settlement: (id: string) => ['settlement', id] as const,
  sellerCash: ['seller-cash'] as const,
  cashManagers: ['cash-managers'] as const,
  dashboardFlags: ['dashboard-flags'] as const,
  refundsDue: ['refunds-due'] as const,
  audits: (filter?: object) => (filter ? ['audits', filter] as const : ['audits'] as const),
  audit: (id: string) => ['audit', id] as const,
};
