/** One key factory per context (CONVENTIONS §7), so invalidation is never a guess. */
export const keys = {
  productTypes: ['product-types'] as const,
  categories: ['categories'] as const,
  products: (filter?: object) => (filter ? ['products', filter] as const : ['products'] as const),
  product: (id: string) => ['product', id] as const,
  skus: (filter?: object) => (filter ? ['skus', filter] as const : ['skus'] as const),
  vendorCodes: ['vendor-codes'] as const,
  vendors: (filter?: object) => (filter ? ['vendors', filter] as const : ['vendors'] as const),
  vendor: (id: string) => ['vendor', id] as const,
  priceLists: ['price-lists'] as const,
  priceList: (id: string) => ['price-list', id] as const,
  discountCeilings: ['discount-ceilings'] as const,
  settings: ['settings'] as const,
  toggles: ['feature-toggles'] as const,
  ceilings: ['ceilings'] as const,
  commissionRates: ['commission-rates'] as const,
  purchaseOrders: (filter?: object) => (filter ? ['purchase-orders', filter] as const : ['purchase-orders'] as const),
  purchaseOrder: (id: string) => ['purchase-order', id] as const,
  incoming: ['incoming'] as const,
  stock: (filter?: object) => (filter ? ['stock', filter] as const : ['stock'] as const),
  skuStock: (id: string) => ['sku-stock', id] as const,
  lots: (lot: string) => ['lots', lot] as const,
  notifications: ['notifications'] as const,
  vehicles: ['vehicles'] as const,
  vehicle: (id: string) => ['vehicle', id] as const,
  loads: (filter?: object) => (filter ? ['vehicle-loads', filter] as const : ['vehicle-loads'] as const),
  vehicleReturns: (id: string) => ['vehicle-returns', id] as const,
  sellers: ['sellers'] as const,
  today: ['attendance-today'] as const,
  attendance: (filter?: object) => (filter ? ['attendance', filter] as const : ['attendance'] as const),
  myVehicle: ['my-vehicle'] as const,
  handovers: ['vehicle-handovers'] as const,
  closingStock: (filter?: object) => (filter ? ['closing-stock', filter] as const : ['closing-stock'] as const),
  zones: ['check-in-zones'] as const,
  stores: (filter?: object) => (filter ? ['stores', filter] as const : ['stores'] as const),
  store: (id: string) => ['store', id] as const,
  storeLedger: (id: string) => ['store-ledger', id] as const,
  storeOptions: ['store-options'] as const,
};
